### ISSUE TITLE
Short tracks (less than 30 seconds)

### ISSUE THREAD

**Issue by heirloomxxz** [TrevTV/mb_ScrobbleItem#1]
Hi!
Is it possible to made available to scrobble tracks which shorter than 30 seconds (like PanoScrobbler at Android or Universal Scrobbler and OpenScrobbler can do)?
Official last.fm scrobbler can scrobble only tracks which is 30 seconds and longer so some tracks from albums with short interludes remains unscrobbled.
Thanx!

**Comment by TrevTV** [comment]
From my minimal testing, it seems to be something inside the code built into MusicBee so a way to bypass it may be a little messy but I'll give it a shot.

**Comment by heirloomxxz** [comment]
Thank you! 🙌

**Comment by TrevTV** [comment]
I wasn't able to fix the autoscrobbling but I was able to fix the plugin so that you could manually scrobble them with this build
[mb_ScrobbleItem.zip](https://github.com/TrevTV/mb_ScrobbleItem/files/8903789/mb_ScrobbleItem.zip)

**Comment by heirloomxxz** [comment]
Worked like a charm! Thank you very much!!! 🔥🔥🔥
