### ISSUE TITLE
Wrong artist scrobbling for compilations

### ISSUE THREAD

**Issue by ant-m-krsk** [TrevTV/mb_ScrobbleItem#2]
Hello! Thanks for plugin!
Can you fix this issues please

1. For compilation-type albums with sogns from various artists artists erroneously scrobbled from tag "Album Artist" instead of "Artist"
In example for Compilation "Armin van Buuren - A State of Trance 2004" (https://www.last.fm/music/Armin+van+Buuren/A+State+of+Trance+2004)

Album Artist: Armin van Buuren
Track: Tranquility
Artist: Mark Otten

It's scrobbled as "Armin van Buuren - Tranquility" instead of "Mark Otten - Tranquility"

2. If album artist is "Various Artists" tracks are not scrobbled at all.

**Comment by TrevTV** [comment]
I believe this should fix it, let me know if you have any issues
[mb_ScrobbleItem.zip](https://github.com/TrevTV/mb_ScrobbleItem/files/9175051/mb_ScrobbleItem.zip)

**Comment by ant-m-krsk** [comment]
Thanks for fix. I tested it and now it does not work completely correctly.

In this version of plugin track scrobbled as "Mark Otten - Tranquility" and it's okay, but tag "Album Artist" is ignored now.
Instead of "Album Artist" it used "Artist" tag for scrobbling and track was scrobbled to album (https://www.last.fm/music/Mark+Otten/A+State+of+Trance+2004) where "Mark Otten" is an "Album Artist".

All tracks from compilations are scrobbled each in their own album where "Album Artist" = "Artists" tag of the track.
And not going together in one album for "Album Artist" tag.

As a result, tracks are scrobbled in many incorrect albums like
https://www.last.fm/music/Mark+Otten/A+State+of+Trance+2004
https://www.last.fm/music/Solid+Globe/A+State+of+Trance+2004
...
etc
 instead of the only correct one https://www.last.fm/music/Armin+van+Buuren/A+State+of+Trance+2004

For "Album Artist" tag = "Various Artists" same behaviour.

**Comment by TrevTV** [comment]
I forgot that last.fm allows you to provide different track and album artist when scrobbling, and from my testing, this allows last.fm to recognize the actual album artist, but with the track artist labeled.
And for the Various Artists issue, that should be fixed as well
[mb_ScrobbleItem.zip](https://github.com/TrevTV/mb_ScrobbleItem/files/9195260/mb_ScrobbleItem.zip)

**Comment by ant-m-krsk** [comment]
Now it works like a charm! :) Thank you
