### ISSUE TITLE
ScrobbleItem seems to not work with the current version

### ISSUE THREAD

**Issue by toomanynights** [TrevTV/mb_ScrobbleItem#4]
Hello,
Unfortunately I can't get ScrobbleItem to work. I am authorized in LastFM in MusicBee (I get new scrobbles automatically), and yet "Scrobble" button does nothing. :(

**Comment by TrevTV** [comment]
I tested it with MusicBee 3.5.8698 and it seems to be working fine. Are you able to attach an error log (`MusicBee -> Help -> Support -> View Error Log`)?

**Comment by toomanynights** [comment]
My apologies, working now. Not sure what is was. Simple, yet amazingly useful plugin, thanks for that.

**Comment by toomanynights** [comment]
Ah. I got it this time.
It works flawlessly if you don't change artist name and/or song title. If you do, however, for some reason it uses the "old" version and therefore, while technically the song is scrobbled, you won't get that scrobble on MusicBee side.

**Comment by toomanynights** [comment]
No, not quite right. I narrowed it down a bit further.
So you have different "artist" field in MB... You have "display artist" and "actual artist". The latter is actually a list, where every item is a singular artist who participated in this song.

Anyway, in some cases you may want to have "display artist" different from "actual artist". For all intents and purposes, you want "display artist" to be considered this song's artist, but you want to have all artists in the database. For example, this could be for correct scrobbling: more often than not, Last.fm only accounts for one artist and not the group.

If that's the case, the plugin unfurtunately will ignore "display artist" and will just combine all "actual artists" instead. Here is what I mean.
![Screenshot 2024-08-08 215629](https://github.com/user-attachments/assets/38aa554d-d2bf-4c51-b3f3-42e43db9fe25)
In this case, instead of expected "Airelle Besson", it will scrobble artist "Airelle Besson, 123".

**Comment by TrevTV** [comment]
Should be fixed in 31b14c54128429660ddf8e69f5de99bad8ec2841, will make a new release soon
