### ISSUE TITLE
Keyboard Shortcut

### ISSUE THREAD

**Issue by BadHumanX** [TrevTV/mb_ScrobbleItem#6]
Thanks so much for this plugins. very useful.
Is there a way I can bind a keyboard key so it can scrobble the selected tracks? 

I could not find one on the hotkeys section of Musicbee
![image](https://github.com/user-attachments/assets/35786403-e5c1-4f6e-9bbf-b9f3ea65b844)

**Comment by TrevTV** [comment]
Added in v1.1.2. The option now exists as `ScrobbleItem: Scrobble Selected`
